services:
  - type: web
    name: ai-interviewer-backend
    env: python
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT ai_interviewer.asgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: "*"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
