# Generated by Django 4.2.23 on 2026-06-24 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills', models.JSONField(default=list)),
                ('nice_to_have', models.JSONField(default=list)),
                ('experience', models.CharField(default='0-2 years', max_length=50)),
                ('responsibilities', models.JSONField(default=list)),
                ('max_questions', models.IntegerField(default=5)),
                ('ats_threshold', models.FloatField(default=50.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('resume_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending ATS'), ('ats_failed', 'ATS Failed'), ('ats_passed', 'ATS Passed'), ('interview_scheduled', 'Interview Scheduled'), ('interview_done', 'Interview Done'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('ats_score', models.FloatField(blank=True, null=True)),
                ('ats_breakdown', models.JSONField(blank=True, null=True)),
                ('interview_thread_id', models.CharField(blank=True, max_length=100)),
                ('interview_report', models.TextField(blank=True)),
                ('interview_rating', models.CharField(blank=True, max_length=50)),
                ('interview_percentage', models.FloatField(blank=True, null=True)),
                ('interview_recommendation', models.CharField(blank=True, max_length=100)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='interviewer.jobposting')),
            ],
        ),
    ]
