# Generated by Django 4.2.23 on 2026-07-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ats_feedback',
            field=models.TextField(blank=True),
        ),
    ]
