# Generated by Django 4.2.23 on 2026-07-10 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviewer', '0002_application_ats_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='candidate_image',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_images/'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
    ]
