# Generated by Django 4.2.23 on 2026-07-10 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interviewer', '0003_application_candidate_image_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='recruiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL),
        ),
    ]
