# Generated by Django 4.2.23 on 2026-07-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0004_jobposting_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='verification_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
