# Generated by Django 4.2.23 on 2026-07-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0005_application_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_disqualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='security_log',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='application',
            name='security_warnings',
            field=models.IntegerField(default=0),
        ),
    ]
