# Generated by Django 6.0.7 on 2026-08-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0006_application_is_disqualified_application_security_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_analytics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_filler_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_speaking_fluency',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_vocab_level',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
