# Generated by Django 6.0.7 on 2026-08-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0007_application_interview_analytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='ats_weights',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
