# Generated by Django 6.0.7 on 2026-08-06 11:55

import interviewer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0008_jobposting_ats_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='custom_questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='security_settings',
            field=models.JSONField(blank=True, default=interviewer.models.default_security_settings),
        ),
    ]
