# Generated by Django 6.0.7 on 2026-08-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0009_jobposting_custom_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='max_followups',
            field=models.IntegerField(default=2),
        ),
    ]
