# Generated by Django 6.0.7 on 2026-08-07 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0010_jobposting_max_followups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_file', models.FileField(upload_to='student_resumes/')),
                ('resume_text', models.TextField(blank=True)),
                ('target_role', models.CharField(blank=True, max_length=200)),
                ('target_jd', models.TextField(blank=True)),
                ('overall_score', models.FloatField(default=0.0)),
                ('formatting_score', models.FloatField(default=0.0)),
                ('font_score', models.FloatField(default=0.0)),
                ('content_score', models.FloatField(default=0.0)),
                ('grammar_score', models.FloatField(default=0.0)),
                ('word_choice_score', models.FloatField(default=0.0)),
                ('feedback_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
