# Generated by Django 6.0.7 on 2026-08-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0011_resumeanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='fixed_resume_file',
            field=models.FileField(blank=True, null=True, upload_to='student_resumes/fixed/'),
        ),
    ]
