# Generated by Django 6.0.7 on 2026-08-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0012_resumeanalysis_fixed_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='fixed_resume_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
