# Generated by Django 6.0.7 on 2026-08-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewer', '0015_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
